-- Drop existing tables to allow clean recreation
DROP TABLE IF EXISTS project_categories CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS organization CASCADE;

-- ========================================
-- Organization Table
-- ========================================
CREATE TABLE organization (
    organization_id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    logo_filename VARCHAR(255) NOT NULL
);

-- ========================================
-- Insert sample data: Organizations
-- ========================================
INSERT INTO organization (name, description, contact_email, logo_filename)
VALUES
('BrightFuture Builders', 'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 'info@brightfuturebuilders.org', 'brightfuture-logo.png'),
('GreenHarvest Growers', 'An urban farming collective promoting food sustainability and education in local neighborhoods.', 'contact@greenharvest.org', 'greenharvest-logo.png'),
('UnityServe Volunteers', 'A volunteer coordination group supporting local charities and service initiatives.', 'hello@unityserve.org', 'unityserve-logo.png');

-- ========================================
-- Projects Table
-- ========================================
CREATE TABLE projects (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    location VARCHAR(255),
    date DATE NOT NULL,
    CONSTRAINT fk_projects_organization
        FOREIGN KEY (organization_id)
        REFERENCES public.organization(organization_id)
);

-- ========================================
-- Insert sample data: Projects
-- ========================================
INSERT INTO projects (organization_id, title, description, location, date)
VALUES
    -- Organization 1
    (1, 'Community Cleanup', 'Work together to clean and restore a local park.', 'Riverside', '2026-10-15'),
    (1, 'Food Drive', 'Collect and distribute food to families in need.', 'Downtown', '2026-10-22'),
    (1, 'School Supply Drive', 'Gather backpacks and school supplies for students.', 'Northside', '2026-11-01'),
    (1, 'Senior Outreach', 'Visit and support elderly community members with practical help.', 'Maple Grove', '2026-11-10'),
    (1, 'Neighborhood Repair', 'Assist with home repairs and basic improvements for families.', 'Oak Valley', '2026-11-20'),

    -- Organization 2
    (2, 'Youth Mentoring', 'Provide mentoring and leadership support for local youth.', 'Westfield', '2026-10-18'),
    (2, 'Community Garden', 'Plant and maintain a garden for families and neighborhoods.', 'Elm Park', '2026-10-27'),
    (2, 'Disaster Prep Workshop', 'Teach emergency preparation and safety skills to the community.', 'Lakeview', '2026-11-05'),
    (2, 'Reading Program', 'Encourage reading and literacy among children and teens.', 'Hillcrest', '2026-11-15'),
    (2, 'Volunteer Day', 'Coordinate a large-scale volunteer service event for the community.', 'Cedar Town', '2026-11-30'),

    -- Organization 3
    (3, 'Medical Outreach', 'Support health education and community wellness services.', 'Sunset Lane', '2026-10-19'),
    (3, 'Housing Support', 'Assist with basic housing assistance and home maintenance projects.', 'Brookside', '2026-10-28'),
    (3, 'Family Resource Fair', 'Connect families with local services and community support.', 'Central Square', '2026-11-03'),
    (3, 'After-School Program', 'Provide tutoring and enrichment activities for students.', 'Greenfield', '2026-11-14'),
    (3, 'Community Wellness Day', 'Host a wellness event with screenings and local services.', 'Harrison', '2026-11-25');

-- ========================================
-- Categories Table
-- ========================================
CREATE TABLE categories (
    category_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

-- ========================================
-- Insert Sample Categories
-- ========================================
INSERT INTO categories (name, description)
VALUES
('Community Service', 'Projects that improve neighborhoods and support local communities.'),
('Education', 'Projects that provide learning opportunities and resources.'),
('Health & Wellness', 'Projects that promote health, safety, and well-being.'),
('Environment', 'Projects focused on sustainability and environmental care.');

-- ========================================
-- Project Categories Junction Table (Many-to-Many)
-- ========================================
CREATE TABLE project_categories (
    project_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY (project_id, category_id),
    CONSTRAINT fk_project_categories_project
        FOREIGN KEY (project_id)
        REFERENCES projects(project_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_project_categories_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
        ON DELETE CASCADE
);

-- ========================================
-- Insert Project-Category Associations
-- ========================================
INSERT INTO project_categories (project_id, category_id)
VALUES
    (1, 1),  -- Community Cleanup: Community Service
    (1, 4),  -- Community Cleanup: Environment
    (2, 1),  -- Food Drive: Community Service
    (2, 3),  -- Food Drive: Health & Wellness
    (3, 1),  -- School Supply Drive: Community Service
    (3, 2),  -- School Supply Drive: Education
    (4, 1),  -- Senior Outreach: Community Service
    (4, 3),  -- Senior Outreach: Health & Wellness
    (5, 1),  -- Neighborhood Repair: Community Service
    (6, 1),  -- Youth Mentoring: Community Service
    (6, 2),  -- Youth Mentoring: Education
    (7, 1),  -- Community Garden: Community Service
    (7, 4),  -- Community Garden: Environment
    (8, 2),  -- Disaster Prep Workshop: Education
    (8, 3),  -- Disaster Prep Workshop: Health & Wellness
    (9, 2),  -- Reading Program: Education
    (10, 1), -- Volunteer Day: Community Service
    (11, 1), -- Medical Outreach: Community Service
    (11, 3), -- Medical Outreach: Health & Wellness
    (12, 1), -- Housing Support: Community Service
    (13, 1), -- Family Resource Fair: Community Service
    (13, 2), -- Family Resource Fair: Education
    (13, 3), -- Family Resource Fair: Health & Wellness
    (14, 2), -- After-School Program: Education
    (15, 1), -- Community Wellness Day: Community Service
    (15, 3); -- Community Wellness Day: Health & Wellness
